version: 2

models:
  - name: dim_channels
    description: "Dimension table for Telegram channels"
    columns:
      - name: channel_id
        description: "Unique channel identifier"
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Human-readable channel name"

  - name: fct_messages
    description: "Fact table for Telegram messages"
    columns:
      - name: message_id
        description: "Unique message identifier"
        tests:
          - unique
          - not_null
      - name: channel_id
        description: "Foreign key to dim_channels"
        tests:
          - not_null
      - name: media_path
        description: "Local path to image if present"
